AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AISSMDoc:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '0.3'
        mainSteps: mainSteps:
  - name: fixIssue
    action: aws:executeAwsApi
    inputs:
      Service: s3
      Api: putPublicAccessBlock
      Parameters:
        Bucket: '{{ BucketName }}'
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      DocumentFormat: YAML
      DocumentType: Automation
      Tags: [{"Key":"Case","Value":"3-AI"}]