AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AISSMDoc:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '0.3'
        mainSteps: mainSteps:
  - name: enableTerminationProtection
    action: aws:executeAwsApi
    inputs:
      Service: cloudformation
      Api: UpdateStack
      Parameters:
        StackName: '{{ StackName }}'
        EnableTerminationProtection: true
  - name: verifyTerminationProtection
    action: aws:executeAwsApi
    inputs:
      Service: cloudformation
      Api: DescribeStacks
      StackName: '{{ StackName }}'
    outputs:
      - Name: TerminationProtectionEnabled
        Selector: $.Stacks[0].EnableTerminationProtection
        Type: Boolean
      DocumentFormat: YAML
      DocumentType: Automation
      Tags: [{"Key":"Case","Value":"3-AI"}]