AWSTemplateFormatVersion: '2010-09-09'
Description: 'SAFETY FALLBACK - CloudTrail should have encryption at-rest enabled'
Resources:
  FallbackDoc:
    Type: AWS::SSM::Document
    Properties:
      Name: Fallback-CloudTrail-should-have-encryption-at-res
      DocumentType: Automation
      Content:
        schemaVersion: '0.3'
        mainSteps:
        - name: SafeNoop
          action: aws:noop