AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CloudFormationStackTerminationProtectionRemediationDoc:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Content:
        schemaVersion: "0.3"
        description: Remediate CloudFormation stacks without termination protection
        parameters:
          StackName:
            type: String
            description: The name of the CloudFormation stack to remediate
        mainSteps:
          - name: EnableTerminationProtection
            action: aws:executeCloudFormationChangeSet
            inputs:
              StackName: "{ StackName }"
              ChangeSetName: EnableTerminationProtection
              Capabilities:
                - CAPABILITY_NAMED_IAM
              Parameters:
                - ParameterKey: EnableTerminationProtection
                  ParameterValue: "true"