AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AISSMDoc:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Content:
        schemaVersion: "0.3"
        description: "Enable termination protection for CloudFormation stacks"
        parameters:
          StackName:
            type: String
            description: "Name of the CloudFormation stack"
        mainSteps:
          - name: "enableProtection"
            action: "aws:executeAwsApi"
            inputs:
              Service: "cloudformation"
              Api: "UpdateTerminationProtection"
              StackName: "{{ StackName }}"
              EnableTerminationProtection: true