AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EC2InstanceMissingTerminationProtectionRemediationDoc:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Content:
        schemaVersion: "0.3"
        description: "Remediate EC2 instance missing required termination protection"
        parameters:
          InstanceId:
            type: String
            description: "The ID of the EC2 instance to remediate"
        mainSteps:
          - name: EnableTerminationProtection
            action: "aws:executeAwsApi"
            inputs:
              Service: "ec2"
              Api: "ModifyInstanceAttribute"
              InstanceId: "{{ InstanceId }}"
              DisableApiTermination: 
                Value: true