AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AISSMDoc:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '0.3'
        description: Enable termination protection for an EC2 instance
        parameters:
          InstanceId:
            type: String
            description: ID of the EC2 instance
        mainSteps:
        - name: protectInstance
          action: aws:executeAwsApi
          inputs:
            Service: ec2
            Api: ModifyInstanceAttribute
            Parameters:
              InstanceId: '{{ .Parameters.InstanceId }}'
              DisableApiTermination:
                Value: true
      DocumentFormat: YAML
      DocumentType: Automation
      Tags:
      - Key: Case
        Value: 3-AI
      - Key: Finding
        Value: EC2 instance missing required termination protection
