AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3BucketPolicyFix:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TargetBucket
      PolicyDocument:
        Statement:
        - Effect: Deny
          Principal: "*"
          Action: "s3:GetObject"
          Resource: !Sub "${TargetBucket}/*"
