AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fallback for IAM User with root user permissions'
Resources:
  RemediationDocument:
    Type: 'AWS::SSM::Document'
    Properties:
      Content:
        schemaVersion: '0.3'
        mainSteps:
        - name: ready
          action: 'aws:noop'
      DocumentFormat: YAML
      DocumentType: Automation
      Name: 'AutoRemediate-IAM-User-with-root-user-permissions'