AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fallback remediation for IAM role trust policy should not allow public access'
Resources:
  RemediationDocument:
    Type: 'AWS::SSM::Document'
    Properties:
      Content:
        schemaVersion: '0.3'
        mainSteps:
        - name: ready
          action: 'aws:noop'
      DocumentFormat: YAML
      DocumentType: Automation
      Name: 'AutoRemediate-IAMroletrustpolicyshouldnotallowpublicac'