AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fallback remediation for RDS DB instances should have deletion protection enabled'
Resources:
  RemediationDocument:
    Type: 'AWS::SSM::Document'
    Properties:
      Content:
        schemaVersion: '0.3'
        mainSteps:
        - name: ready
          action: 'aws:noop'
      DocumentFormat: YAML
      DocumentType: Automation
      Name: 'AutoRemediate-RDS-DB-instances-should-have-deletion-pr'