AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fallback remediation for S3 general purpose buckets should require requests to use SSL'
Resources:
  RemediationDocument:
    Type: 'AWS::SSM::Document'
    Properties:
      Content:
        schemaVersion: '0.3'
        mainSteps:
        - name: ready
          action: 'aws:noop'
      DocumentFormat: YAML
      DocumentType: Automation
      Name: 'AutoRemediate-S3-general-purpose-buckets-should-requir'